// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: api/loan/loan.proto

package loan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueLoanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId string `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *IssueLoanRequest) Reset() {
	*x = IssueLoanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_loan_loan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLoanRequest) ProtoMessage() {}

func (x *IssueLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_loan_loan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLoanRequest.ProtoReflect.Descriptor instead.
func (*IssueLoanRequest) Descriptor() ([]byte, []int) {
	return file_api_loan_loan_proto_rawDescGZIP(), []int{0}
}

func (x *IssueLoanRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *IssueLoanRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IssueLoanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoanId string `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
}

func (x *IssueLoanResponse) Reset() {
	*x = IssueLoanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_loan_loan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLoanResponse) ProtoMessage() {}

func (x *IssueLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_loan_loan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLoanResponse.ProtoReflect.Descriptor instead.
func (*IssueLoanResponse) Descriptor() ([]byte, []int) {
	return file_api_loan_loan_proto_rawDescGZIP(), []int{1}
}

func (x *IssueLoanResponse) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

type ReturnLoanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoanId string `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
}

func (x *ReturnLoanRequest) Reset() {
	*x = ReturnLoanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_loan_loan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnLoanRequest) ProtoMessage() {}

func (x *ReturnLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_loan_loan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnLoanRequest.ProtoReflect.Descriptor instead.
func (*ReturnLoanRequest) Descriptor() ([]byte, []int) {
	return file_api_loan_loan_proto_rawDescGZIP(), []int{2}
}

func (x *ReturnLoanRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

type ReturnLoanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ReturnLoanResponse) Reset() {
	*x = ReturnLoanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_loan_loan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnLoanResponse) ProtoMessage() {}

func (x *ReturnLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_loan_loan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnLoanResponse.ProtoReflect.Descriptor instead.
func (*ReturnLoanResponse) Descriptor() ([]byte, []int) {
	return file_api_loan_loan_proto_rawDescGZIP(), []int{3}
}

func (x *ReturnLoanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_loan_loan_proto protoreflect.FileDescriptor

var file_api_loan_loan_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x10, 0x49, 0x73, 0x73, 0x75, 0x65, 0x4c, 0x6f,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x49,
	0x73, 0x73, 0x75, 0x65, 0x4c, 0x6f, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x6c, 0x6f, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x4c, 0x6f, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x6c, 0x6f, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x4c, 0x6f, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x78, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x49, 0x73, 0x73, 0x75, 0x65, 0x4c,
	0x6f, 0x61, 0x6e, 0x12, 0x11, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x4c, 0x6f, 0x61, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x4c, 0x6f,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x4c, 0x6f, 0x61, 0x6e, 0x12, 0x12, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x4c, 0x6f, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x4c, 0x6f, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_loan_loan_proto_rawDescOnce sync.Once
	file_api_loan_loan_proto_rawDescData = file_api_loan_loan_proto_rawDesc
)

func file_api_loan_loan_proto_rawDescGZIP() []byte {
	file_api_loan_loan_proto_rawDescOnce.Do(func() {
		file_api_loan_loan_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_loan_loan_proto_rawDescData)
	})
	return file_api_loan_loan_proto_rawDescData
}

var file_api_loan_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_loan_loan_proto_goTypes = []any{
	(*IssueLoanRequest)(nil),   // 0: IssueLoanRequest
	(*IssueLoanResponse)(nil),  // 1: IssueLoanResponse
	(*ReturnLoanRequest)(nil),  // 2: ReturnLoanRequest
	(*ReturnLoanResponse)(nil), // 3: ReturnLoanResponse
}
var file_api_loan_loan_proto_depIdxs = []int32{
	0, // 0: LoanService.IssueLoan:input_type -> IssueLoanRequest
	2, // 1: LoanService.ReturnLoan:input_type -> ReturnLoanRequest
	1, // 2: LoanService.IssueLoan:output_type -> IssueLoanResponse
	3, // 3: LoanService.ReturnLoan:output_type -> ReturnLoanResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_loan_loan_proto_init() }
func file_api_loan_loan_proto_init() {
	if File_api_loan_loan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_loan_loan_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IssueLoanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_loan_loan_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IssueLoanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_loan_loan_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnLoanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_loan_loan_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnLoanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_loan_loan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_loan_loan_proto_goTypes,
		DependencyIndexes: file_api_loan_loan_proto_depIdxs,
		MessageInfos:      file_api_loan_loan_proto_msgTypes,
	}.Build()
	File_api_loan_loan_proto = out.File
	file_api_loan_loan_proto_rawDesc = nil
	file_api_loan_loan_proto_goTypes = nil
	file_api_loan_loan_proto_depIdxs = nil
}
